-- Options are automatically loaded before lazy.nvim startup Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here

-- Added clipboard support for wsl2 client

-- if vim.fn.has("wsl") then
--   vim.g.clipboard = {
--     name = "win_clipboard",
--     copy = {
--       ["+"] = "clip.exe",
--       ["*"] = "clip.exe",
--     },
--     paste = {
--       ["+"] = "powershell.exe Get-Clipboard",
--       ["*"] = "powershell.exe Get-Clipboard",
--     },
--     cache_enabled = 0,
--   }
--
--   vim.keymap.set({ "n", "v" }, "y", '"+y', { noremap = true, silent = true })
--   vim.keymap.set({ "n", "v" }, "p", '"+p', { noremap = true, silent = true })
-- end
--
-- This settings lets clangd to work with utf-16 files
-- local capabilities = vim.lsp.protocol.make_client_capabilities()
-- capabilities.offsetEncoding = { "utf-16" }
-- require("lspconfig").clangd.setup({ capabilities = capabilities })
